name: CI-brk
on: 
    repository_dispatch:
    workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Gist
      id: get
      uses: bshener/gist@master
      with:
        gistURL: "https://gist.github.com/bshener/857d766309c45645838dbf040d9aea7e" 
    - name: Show Gist contents
      id: run
      run: |
        cat ${{ steps.get.outputs.file }}
