name: CI-brk
on: 
    repository_dispatch:
    workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Gist
      id: get
      uses: bshener/gist@master
      with:
        gistURL: "https://gist.github.com/andymckay/c290f9c904502e98da98e59124610b93" 
    - name: Show Gist contents
      id: run
      run: |
        cat ${{ steps.get.outputs.file }}
